/* Replace with your SQL commands */-- USE `fitnessvworkdb` ;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `authtoken`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `favourites_user_food_mapper`;
DROP TABLE IF EXISTS `food_items`;
DROP TABLE IF EXISTS `restaurant_categories_mapper`;
DROP TABLE IF EXISTS `restaurants`;
DROP TABLE IF EXISTS `user`;
SET foreign_key_checks = 1;
